In [13]:
import pandas as pd 
from sklearn.decomposition import PCA
import numpy as np
from sklearn import datasets

#### Lets try to convert the digit dataframe to pd.DataFrame

In [14]:
digits=datasets.load_digits()
cols=digits.feature_names
df=pd.DataFrame(digits.data,columns=cols)
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [15]:
# Its normally as numpy array saved
digits.data


array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [16]:
num_df=df.to_numpy()
num_df

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

#### **Covarinz Matrix:**

In [18]:
# Covariance:
cov=np.matmul(np.transpose(digits.data),digits.data)
cov

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 1.64400e+03, 7.15400e+03, ..., 3.40600e+03,
        1.30600e+03, 6.60000e+01],
       [0.00000e+00, 7.15400e+03, 8.92850e+04, ..., 6.11890e+04,
        2.18770e+04, 4.72000e+03],
       ...,
       [0.00000e+00, 3.40600e+03, 6.11890e+04, ..., 1.44749e+05,
        5.32400e+04, 9.59500e+03],
       [0.00000e+00, 1.30600e+03, 2.18770e+04, ..., 5.32400e+04,
        3.77360e+04, 9.83300e+03],
       [0.00000e+00, 6.60000e+01, 4.72000e+03, ..., 9.59500e+03,
        9.83300e+03, 6.45300e+03]])

#### **Basiswechsel Using SVD mit numpy:**

In [29]:
digits_centerd=digits.data - digits.data.mean(axis=0)
U,s,Vt=np.linalg.svd(digits_centerd)

In [34]:
print(f"Die Linke Matrix unsere Singulärwertzerlegung is U und hat den shape: {U.shape}")
print(f"Die rechte Matrix unsere Singulärwertzerlegung is V^T und hat den shape: {Vt.shape}")


Die Linke Matrix unsere Singulärwertzerlegung is U und hat den shape: (1797, 1797)
Die rechte Matrix unsere Singulärwertzerlegung is V^T und hat den shape: (64, 64)


In [44]:
# s will give just the sigmas values:
# So we have to convert it into a matrix that fits my 
# So s has to get the shape of (1797,64)
print(s.shape)
s

(64,)


array([5.67006567e+02, 5.42251854e+02, 5.04630594e+02, 4.26117676e+02,
       3.53335033e+02, 3.25820366e+02, 3.05261580e+02, 2.81160331e+02,
       2.69069782e+02, 2.57823951e+02, 2.26318797e+02, 2.21514832e+02,
       1.98330715e+02, 1.95700139e+02, 1.77976271e+02, 1.74460791e+02,
       1.68727876e+02, 1.64158492e+02, 1.48233309e+02, 1.39831325e+02,
       1.38584433e+02, 1.31188207e+02, 1.28726917e+02, 1.24931590e+02,
       1.22575034e+02, 1.13444877e+02, 1.11480271e+02, 1.05463488e+02,
       1.02807802e+02, 9.62285662e+01, 8.98129647e+01, 8.73349465e+01,
       8.52596044e+01, 8.41567134e+01, 8.15893653e+01, 7.96420046e+01,
       7.44304714e+01, 7.01219569e+01, 6.92755923e+01, 6.75640682e+01,
       6.40331590e+01, 5.85269779e+01, 5.71281856e+01, 5.50924318e+01,
       5.01790999e+01, 4.81749428e+01, 4.56228649e+01, 4.08958572e+01,
       3.46850352e+01, 2.95461187e+01, 2.12889966e+01, 1.33446026e+01,
       1.06481402e+01, 1.04443771e+01, 8.44041164e+00, 5.18181553e+00,
      

In [50]:
smat=np.zeros(digits.data.shape)
smat[:64,:64]=np.diag(s)
smat

array([[567.0065665 ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 542.25185421,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 504.63059421, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [51]:
# Lets check if out data and the SVD almost the same
np.allclose(digits_centerd, U @ smat @ Vt)

True

#### **Projektion on some pricipal coponents:**
First of all dont forget that Vt is already transposed so the vectors v1,v2,.. on rows not columns 

In [54]:
projection_matrix=Vt.T[:,:2]
projection_matrix.shape

(64, 2)

In [55]:
projected_data= digits_centerd @ projection_matrix
projected_data

array([[  1.25946645, -21.27488348],
       [ -7.9576113 ,  20.76869896],
       [ -6.99192297,   9.95598641],
       ...,
       [-10.8012837 ,   6.96025223],
       [  4.87210009, -12.42395362],
       [  0.34438963,  -6.36554919]])

#### **Lets do the same with PCA:**

In [56]:
from sklearn.decomposition import PCA

In [57]:
pca=PCA(n_components=2)
X2D=pca.fit_transform(digits.data)

In [58]:
X2D

array([[ -1.25946464,  21.27488257],
       [  7.95761092, -20.768708  ],
       [  6.99192152,  -9.95598343],
       ...,
       [ 10.80128563,  -6.96024597],
       [ -4.8721002 ,  12.42395015],
       [ -0.34438856,   6.36556281]])

In [59]:
pca.explained_variance_ratio_

array([0.14890594, 0.13618771])

In [61]:
# n_components=0.95 means the I need 95% of variance to be clared with my projected data
pca = PCA(n_components=0.95)
digits_max_variance = pca.fit_transform(digits.data)
pca.explained_variance_ratio_

array([0.14890594, 0.13618771, 0.11794594, 0.08409979, 0.05782415,
       0.0491691 , 0.04315987, 0.03661373, 0.03353248, 0.03078806,
       0.02372341, 0.02272697, 0.01821863, 0.01773855, 0.01467101,
       0.01409716, 0.01318589, 0.01248138, 0.01017718, 0.00905617,
       0.00889538, 0.00797123, 0.00767493, 0.00722904, 0.00695889,
       0.00596081, 0.00575615, 0.00515158, 0.0048954 ])